config/routes.rb
Rails.application.routes.draw do
  get 'braintree/client_token'

  post 'braintree/checkout'

  root to: "home#index"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/braintree_controller.rb
class BraintreeController < ApplicationController
  def client_token
    client_token = Braintree::ClientToken.generate
    render json: {client_token: client_token}
  end

  def checkout
    nonce_from_the_client = params[:checkout_form][:payment_method_nonce]
    result = Braintree::Transaction.sale(
      :amount => "10.00",
      :payment_method_nonce => nonce_from_the_client,
      :options => {
        :submit_for_settlement => true
      }
    )
    transaction = result.transaction
    logger.ap transaction

    redirect_to :root, flash: {notice: transaction && transaction.status}
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/braintree_helper.rb
module BraintreeHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<% if flash[:notice] %>
  <div class="notice"><%= flash[:notice] %></div>
<% end %>

<div class="credit-card-form">
  <%= form_for :checkout_form, url: braintree_checkout_path, html: { id: "checkout-form" } do |form| %>
    <div id="error-message"></div>

    <%= form.label :card_number, "Credit Card Number" %>
    <div class="hosted-field" id="card-number">
    </div>

    <%= form.label :cvv, "CVV" %>
    <div class="hosted-field" id="cvv">
    </div>

    <%= form.label :expiration_date, "Expiration Date" %>
    <div class="hosted-field" id="expiration-date">
    </div>

    <%= form.hidden_field "payment_method_nonce" %>
    <%= form.submit "Give me $10.00", disabled: true, class: "btn btn-primary" %>
    <div class="clearfix"></div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Day2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="https://js.braintreegateway.com/web/3.3.0/js/client.min.js"></script>
  <script src="https://js.braintreegateway.com/web/3.3.0/js/hosted-fields.min.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>